# Generated by Django 5.0.4 on 2024-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="best_sellers",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
