# Generated by Django 5.0.4 on 2024-06-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_drug_best_sellers"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="price_id",
            field=models.TextField(default="timezone.now"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="drug",
            name="image",
            field=models.ImageField(upload_to="drug_images/"),
        ),
    ]
