# Generated by Django 5.0.4 on 2024-06-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_drug_price_id_alter_drug_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="description_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_fr",
            field=models.TextField(null=True),
        ),
    ]
