# Generated by Django 5.0.4 on 2024-06-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_drug_description_de_drug_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_be",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_ch",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_cn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_it",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_jp",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_nl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_pt",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_sv",
            field=models.TextField(null=True),
        ),
    ]
