# Generated by Django 5.0.4 on 2024-06-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_drug_description_ar_drug_description_be_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drug",
            old_name="description_en",
            new_name="description_en_au",
        ),
        migrations.AddField(
            model_name="drug",
            name="description_en_ca",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_en_sg",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_en_uk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="description_en_us",
            field=models.TextField(null=True),
        ),
    ]
