# Generated by Django 5.0.4 on 2024-06-22 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_rename_description_en_drug_description_en_au_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drug",
            old_name="description_jp",
            new_name="description_pr",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="description_pt",
        ),
    ]
