# Generated by Django 5.0.4 on 2024-06-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_rename_description_jp_drug_description_pr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="description_jp",
            field=models.TextField(null=True),
        ),
    ]
