# Generated by Django 5.0.4 on 2024-06-22 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_rename_description_be_drug_description_de_ch_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drug",
            old_name="description_cn",
            new_name="description_zh_cn",
        ),
    ]
