# Generated by Django 5.0.4 on 2024-06-22 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_rename_description_cn_drug_description_zh_cn"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drug",
            old_name="description_jp",
            new_name="description_jpy",
        ),
    ]
