# Generated by Django 5.0.4 on 2024-06-22 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_rename_description_jp_drug_description_jpy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drug",
            old_name="description_zh_cn",
            new_name="description_zh_CN",
        ),
    ]
