# Generated by Django 5.0.4 on 2024-06-22 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_rename_description_zh_cn_drug_description_zh_cn"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drug",
            old_name="description_zh_CN",
            new_name="description_zh_hans",
        ),
    ]
