# Generated by Django 5.0.4 on 2024-06-22 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_rename_description_zh_cn_drug_description_zh_hans"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drug",
            old_name="description_jpy",
            new_name="description_ja",
        ),
    ]
