# Generated by Django 5.0.4 on 2024-06-22 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_rename_description_jpy_drug_description_ja"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drug",
            old_name="description_zh_hans",
            new_name="description_zh_Hans",
        ),
    ]
