# Generated by Django 5.0.4 on 2024-06-23 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_drug_price_ar_drug_price_de_drug_price_de_ch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drug",
            name="price_id",
        ),
    ]
