# Generated by Django 5.0.4 on 2024-06-23 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_remove_drug_price_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drug",
            name="price_ar",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_de",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_de_CH",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_en_au",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_en_ca",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_en_sg",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_en_uk",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_en_us",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_es",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_fr",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_it",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_ja",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_nl",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_nl_BE",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_pt",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_ru",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_sv",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_zh_Hans",
        ),
    ]
