# Generated by Django 5.0.4 on 2024-06-23 23:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0022_drug_price_ar_drug_price_de_drug_price_de_ch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drug",
            name="description_zh_Hans",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="price_zh_Hans",
        ),
    ]
