# Generated by Django 5.0.4 on 2024-06-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0023_remove_drug_description_zh_hans_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="description_zh_Hans",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="price_zh_Hans",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
