# Generated by Django 5.0.4 on 2024-06-24 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0024_drug_description_zh_hans_drug_price_zh_hans"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drug",
            old_name="description_zh_Hans",
            new_name="description_zh_hans",
        ),
        migrations.RenameField(
            model_name="drug",
            old_name="price_zh_Hans",
            new_name="price_zh_hans",
        ),
    ]
