# Generated by Django 5.0.4 on 2024-06-24 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0025_rename_description_zh_hans_drug_description_zh_hans_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drug",
            old_name="description_de_CH",
            new_name="description_de_ch",
        ),
        migrations.RenameField(
            model_name="drug",
            old_name="price_de_CH",
            new_name="price_de_ch",
        ),
    ]
