# Generated by Django 5.0.4 on 2024-06-24 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0026_rename_description_de_ch_drug_description_de_ch_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drug",
            old_name="description_nl_BE",
            new_name="description_nl_be",
        ),
        migrations.RenameField(
            model_name="drug",
            old_name="price_nl_BE",
            new_name="price_nl_be",
        ),
    ]
