# Generated by Django 5.0.4 on 2024-06-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0028_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="content_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_de_ch",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_en_au",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_en_ca",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_en_sg",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_en_uk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_en_us",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_it",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_ja",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_nl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_nl_be",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_pt",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_sv",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_zh_hans",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_de_ch",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_en_au",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_en_ca",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_en_sg",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_en_uk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_en_us",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_it",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_ja",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_nl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_nl_be",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_pt",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_sv",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description_zh_hans",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_de",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_de_ch",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_en_au",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_en_ca",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_en_sg",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_en_uk",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_en_us",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_es",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_it",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_ja",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_nl",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_nl_be",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_pt",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_sv",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_zh_hans",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
