# Generated by Django 5.0.4 on 2024-06-28 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0029_blogpost_content_ar_blogpost_content_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_first_name", models.CharField(max_length=100)),
                ("billing_last_name", models.CharField(max_length=100)),
                (
                    "billing_company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("billing_country", models.CharField(max_length=100)),
                ("billing_street_address", models.CharField(max_length=255)),
                ("billing_town_city", models.CharField(max_length=100)),
                ("billing_state", models.CharField(max_length=100)),
                ("billing_zipcode", models.CharField(max_length=20)),
                ("billing_phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "order_note",
                    models.CharField(blank=True, max_length=2056, null=True),
                ),
                ("create_account", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_first_name", models.CharField(max_length=100)),
                ("shipping_last_name", models.CharField(max_length=100)),
                (
                    "shipping_company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("shipping_country", models.CharField(max_length=100)),
                ("shipping_street_address", models.CharField(max_length=255)),
                ("shipping_town_city", models.CharField(max_length=100)),
                ("shipping_state", models.CharField(max_length=100)),
                ("shipping_zipcode", models.CharField(max_length=20)),
                ("shipping_phone_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.billingdetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.shippingaddress",
                    ),
                ),
            ],
        ),
    ]
