# choices.py
CATEGORIES = [
    ('OTC', 'Over The Counter'),
    ('Prescription', 'Prescription'),
    ('Herbal', 'Herbal'),
    ('Vitamins', 'Vitamins'),
    ('Supplements', 'Supplements'),
    ('Homeopathic', 'Homeopathic'),
    ('Ayurvedic', 'Ayurvedic'),
    ('Traditional Chinese Medicine', 'Traditional Chinese Medicine'),
    ('Nutraceuticals', 'Nutraceuticals'),
    ('Antibiotics', 'Antibiotics'),
    ('Analgesics', 'Analgesics'),
    ('Antidepressants', 'Antidepressants'),
    ('Antihistamines', 'Antihistamines'),
    ('Cardiovascular', 'Cardiovascular'),
    ('Diabetes', 'Diabetes'),
    ('Gastrointestinal', 'Gastrointestinal'),
    ('Dermatological', 'Dermatological'),
    ('Respiratory', 'Respiratory'),
    ('Neurological', 'Neurological'),
    ('Oncology', 'Oncology'),
    ('Endocrine', 'Endocrine'),
    ('Pediatric', 'Pediatric'),
    ('Geriatric', 'Geriatric'),
    ("Women's Health", "Women\'s Health"),
    ("Men's Health", "Men\'s Health"),
    ('Ophthalmic', 'Ophthalmic'),
    ('Dental', 'Dental'),
    ('Veterinary', 'Veterinary'),
]
